# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


### Encoding categorical data

Label Encoding the "Gender" column

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


One Hot Encoding the "Geography" column

In [8]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])] , remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


### Splitting the dataset into the Training set and Test set

In [10]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [11]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

## Part 2 - Building the ANN

### Initializing the ANN

In [12]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '1' # Hide info messages

ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))
# use sigmoid activation to get propability for binary output
# use softmax activation for categorical output

## Part 3 - Training the ANN

### Compiling the ANN

In [16]:
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
# use binary_crossentropy for binary output
# use categorical_crossentropy for categorical output

### Training the ANN on the Training set

In [17]:
ann.fit(X_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.7287 - accuracy: 0.5153
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.5117 - accuracy: 0.8044
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4659 - accuracy: 0.8062
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4459 - accuracy: 0.8060
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4394 - accuracy: 0.8030
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8196
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3992 - accuracy: 0.8262
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4032 - accuracy: 0.8227
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3937 - accuracy: 0.8317
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3819 - accura

## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Homework**

Use our ANN model to predict if the customer with the following informations will leave the bank: 

Geography: France

Credit Score: 600

Gender: Male

Age: 40 years old

Tenure: 3 years

Balance: \$ 60000

Number of Products: 2

Does this customer have a credit card? Yes

Is this customer an Active Member: Yes

Estimated Salary: \$ 50000

So, should we say goodbye to that customer?

**Solution**

In [18]:
df = pd.DataFrame(columns=dataset.columns)
print(df)

Empty DataFrame
Columns: [RowNumber, CustomerId, Surname, CreditScore, Geography, Gender, Age, Tenure, Balance, NumOfProducts, HasCrCard, IsActiveMember, EstimatedSalary, Exited]
Index: []


In [19]:
dict = {
    'Geography': 'France',
    'CreditScore': 600,
    'Gender': 'Male',
    'Age': 40,
    'Tenure': 3,
    'Balance': 60000,
    'NumOfProducts': 2,
    'HasCrCard': 1,
    'IsActiveMember': 1,
    'EstimatedSalary': 50000
}

df = df.append(dict, ignore_index = True)

X_single = df.iloc[:, 3:-1].values

X_single[:, 2] = le.transform(X_single[:, 2])

X_single = np.array(ct.transform(X_single))

X_single = sc.transform(X_single)

prediction = ann.predict(X_single)[0][0]

print("Churn probability: {:.2f} %".format(prediction*100))
print("Should we say goodbye? Answer: {}".format(prediction > 0.5) )

Churn probability: 2.43 %
Should we say goodbye? Answer: False


Therefore, our ANN model predicts that this customer stays in the bank!

### Predicting the Test set results

In [20]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
# evaluate performance by comparing the predicted exit event and the ground truth
print(np.concatenate(
    (
        y_pred.reshape(len(y_pred), 1),
        y_test.reshape(len(y_test), 1)
    ),
    axis=1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


### Making the Confusion Matrix

In [21]:
from sklearn.metrics import confusion_matrix, accuracy_score, precision_score, recall_score, f1_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
print('Accuracy: {0:.2g}'.format(accuracy_score(y_test, y_pred)))
print('Precision: {0:.2g}'.format(precision_score(y_test, y_pred)))
print('Recall: {0:.2g}'.format(recall_score(y_test, y_pred)))
print('F1 Score: {0:.2g}'.format(f1_score(y_test, y_pred)))

[[1497   98]
 [ 188  217]]
Accuracy: 0.86
Precision: 0.69
Recall: 0.54
F1 Score: 0.6
